name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 9.15.5

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 20.19.0

      - name: install dep
        run: pnpm i

      - name: run lint
        run: pnpm eslint .
