name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 9.15.5
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.19.0

      - name: Install Dependencies
        run: pnpm i 

      - name: Build
        run: pnpm -F "*" build

      - name: Push to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore(release): publish"
          title: "chore(release): publish"
          version: pnpm changeset version
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.I18N }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}